### PR TITLE
Fix data path for py3.9 updates

### PR DESCRIPTION
**Pull request by dcslagel**
#### Description:

Updating the local python version to 3.9 reveals an error in the get_data_path() function.
```
python tutorial/example.py
TypeError: get_data_path() missing 1 required positional argument: 'datafile'``
```

This change updates the get_data_path() function work with Python 3.9
- Make alaska/data a module by adding __init__.py
- Use data module in importlib path command to retrieve the path of a passed in file in the data directory.

**Reminders**

- [X] Run `black .` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [X] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

#### Testing:

This has be tested on dev-env and wheel packages for Python 3.6, 3.8 and Python 3.9 by running the pytest suite at the GIT_ROOT.

```
Name                           Stmts   Miss  Cover
--------------------------------------------------
alaska/__init__.py                 6      0   100%
alaska/_version.py               279    142    49%
alaska/data/__init__.py            0      0   100%
alaska/get_data_path.py            8      2    75%
alaska/keyword_tree.py           296      4    99%
alaska/model.py                  303    115    62%
alaska/params.py                  56      0   100%
alaska/predict_from_model.py      86     23    73%
alaska/utils.py                  324    103    68%
--------------------------------------------------
TOTAL                           1358    389    71%
```

Let me know if this change could be accepted (or rejected) or
needs some additional changes before being approved and merged.

Thank you,
DC

### CODE REVIEW

**Review by jessepisel — COMMENTED** [review]
Thanks for the changes @dcslagel I have gone though and they all look like they are working with the data path changes. the only thing I have for this review is did you mean to push `__init__.py` to the data directory with nothing in the file?

**Comment by dcslagel** [comment]
Hi @jessepisel,  

Good question!.  Yes, the empty __init.py in the data directory causes python to treat the data directory as a sub package of Alaska, enabling us to do `from alaska import data`,  and avoiding a bunch of brittle path wrangling.

DC

**Comment by jessepisel** [comment]
Perfect, I just wanted to make sure before I merged it in. Thanks for all your work on organizing the data paths. This takes care of a lot of issues!
